# Use root/example as user/password credentials
version: '2'

services:

  site1:
    image: httpd
    restart: always
    volumes:
      - ${PWD}/site1:/usr/local/apache2/htdocs/
    ports:
      - "8081:80"

  site2:
    image: httpd
    restart: always
    volumes:
      - ${PWD}/site2:/usr/local/apache2/htdocs/
    ports:
      - "8082:80"

  site3:
    image: httpd
    restart: always
    volumes:
      - ${PWD}/site3:/usr/local/apache2/htdocs/
    ports:
      - "8083:80"
