# Use root/example as user/password credentials
version: '2'

services:

  db:
    image: centos/mysql-57-centos7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - /root/docker-mysql/data:/var/lib/mysql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8880:8080"
