version: '2'

networks:
  gitlab:

services:
  gitlab:
    image: gitlab/gitlab-ce
    hostname: 'gitlab.example.com'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
    ports:
        - "443:10443"
        - "80:10080"
        - "22:10022"
    volumes:
        - /root/docker-gitlab/config:/etc/gitlab
        - /root/docker-gitlab/logs:/var/log/gitlab
        - /root/docker-gitlab/data:/var/opt/gitlab
    networks:
      - gitlab
    #restart: always        

