version: '2'

networks:
  teamcitynet:

services:
  teamcity:
    image: jetbrains/teamcity-server
    ports:
        - "8888:8111"
    volumes:
        - /root/docker-teamcity/datadir/:/data/teamcity_server/datadir
        - /root/docker-teamcity/logs/:/opt/teamcity/logs
    networks:
      - teamcitynet
    depends_on: 
    - db

  db:
    image: postgres:9.4
    ports:
        - "5432:5432"
    networks:
      - teamcitynet
    volumes:
      - /root/docker-teamcity/db/:/var/lib/postgresql
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser

